name: Node deploy

on: 
  push: 
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: show files
        run: |
          ls -a
          echo ${{secrets.ROOTPATH}}
      - name: copy dir to remote server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}  
          PASSWORD : ${{ secrets.PASSWORD }}     
        with:
          source: ${{secrets.SOURCE}}
          target: ${{secrets.ROOTPATH}} 
         

          